import Link from "next/link";

export default function Experience() {
  return <main>
    <section className="inner-hero"><div className="wrap inner-grid"><div><span className="eyebrow">The 24-hour experience</span><h1 className="serif section-heading">A splendid day<br/>off the balance sheet.</h1><p>Wealth brings assets worth enjoying. It also demands attention to their risks, condition and value. For one day, the trustee takes that responsibility.</p><a href="/enroll" className="btn btn-gold">Curate your day</a></div><div className="inner-photo tea-photo" role="img" aria-label="A peaceful tea moment on a yacht"/></div></section>
    <section className="section"><div className="wrap"><span className="eyebrow">The collection</span><h2 className="serif section-heading">What is included.</h2><div className="product-grid"><article className="product-card"><span className="eyebrow">The signature experience</span><h3 className="serif">The Wealth Holiday</h3><p>List your holdings. Review the trust instrument and apply your signature. For 24 hours, the trustee oversees the risks and care of the estate while a license preserves your use of everything.</p><div className="product-bottom"><strong>$249 <small>illustrative only</small></strong><a href="/enroll">Choose experience</a></div></article><article className="product-card accent-card"><span className="eyebrow">Optional add-on</span><h3 className="serif">Nothing Licensed Back</h3><p>For 24 hours, no use license is issued for listed possessions, accounts or discretionary spending. Automatic payments already in motion continue.</p><div className="product-bottom"><strong>+$99 <small>illustrative only</small></strong><a href="/enroll?addon=no-license">Add to my day</a></div></article><article className="product-card"><span className="eyebrow">Optional add-on</span><h3 className="serif">The Companion Release</h3><p>Invite a friend or family member to the same holiday. They prepare their own schedule and sign their own instrument.</p><div className="product-bottom"><strong>+$149 <small>illustrative only</small></strong><a href="/enroll?addon=companion">Invite someone</a></div></article></div></div></section>
    <section className="gift-band"><div className="wrap gift-band-grid"><div><span className="eyebrow">A gift of perspective</span><h2 className="serif section-heading">Give a day of nothing.</h2><p>For the person who has everything: an exquisitely understated gift card inviting them to set the entire collection down for a day. The recipient decides what to list and whether to participate.</p><a href="/enroll?mode=gift" className="btn btn-light">Create a gift card</a></div><div className="gift-preview"><div className="gift-preview-top"><span className="brand-mark">G</span><span>PRIVATE INVITATION · 24 HOURS</span></div><div className="serif gift-preview-title">The gift of<br/>having nothing.</div><div className="gift-preview-bottom">GIVEAWAYMYWEALTH.COM <span>NO. 001 / PRIVATE</span></div></div></div></section>
    <section className="section"><div className="wrap intro-grid"><div><span className="eyebrow">For the younger generation</span><h2 className="serif section-heading">No portfolio?<br/>Give away a sibling.</h2></div><div><p className="lead">Our Junior Office accepts brothers and sisters for an impeccably documented 24-hour holiday.</p><p className="body">Select the sibling, state their chief offense, and collect a certificate worthy of framing above the toy chest. No names or payment details required.</p><Link href="/children" className="btn btn-dark">Visit the Junior Office</Link></div></div></section>
    <section className="section worry-section"><div className="wrap narrow"><span className="eyebrow">A precise distinction</span><h2 className="serif section-heading">A day without stewardship.</h2><p className="large-copy">The standard arrangement separates the enjoyment of an asset from the responsibility for its care and value. With Nothing Licensed Back, you set aside its use as well for the 24-hour term.</p><Link href="/arrangement" className="btn btn-outline">Read the arrangement</Link></div></section>
  </main>;
}
