import Link from "next/link";

export default function Home() {
  return <main>
    <section className="home-hero">
      <div className="hero-copy"><span className="eyebrow">A private holiday from ownership</span><h1 className="serif">All yours.<br/><em>Someone else’s mental burden.</em></h1><p>For twenty-four exquisite hours, you keep the use of what you own. Our trustee takes responsibility for its liabilities, its upkeep, and preserving its value—and shoulders the mental burden of keeping track of it all.</p><a href="/enroll" className="btn btn-gold">Begin your 24 hours <span aria-hidden="true">↗</span></a></div>
      <div className="hero-image" role="img" aria-label="Elegant yacht on the Atlantic coast with friends enjoying the afternoon"><span className="image-stamp">The art of temporary nothing</span></div>
    </section>
    <div className="ribbon">One day of freedom &nbsp; · &nbsp; 24 hours of exquisite perspective &nbsp; · &nbsp; Everything returns at the end</div>
    <section className="section"><div className="wrap intro-grid"><div><span className="eyebrow">The proposition</span><h2 className="serif section-heading">A little less<br/>to carry.</h2></div><div><p className="lead">Imagine enjoying the yacht without worrying about liability or maintenance. The property without weighing every operating risk and capital need. The portfolio without the constant uncertainty of market fluctuations, long-term value, and growing capital.</p><p className="body">Our trustee accepts your itemized estate for one day, taking on the risks and responsibilities that accompany it. A license lets you keep enjoying the assets while their care and preservation become our trustee’s concern. For 24 hours, enjoy a sadhu’s freedom from worldly possessions and the joy of having nothing to manage, with no lifetime vow and, unusually, continued use of the yacht.</p><Link className="btn btn-outline" href="/experience">Explore the experience</Link></div></div></section>
    <section className="section worry-section"><div className="wrap"><span className="eyebrow">An exercise in perspective</span><h2 className="serif section-heading">How much can a worry weigh?</h2><div className="worry-grid"><div className="worry-pane"><span className="eyebrow">Before</span><h3>A kingdom’s<br/>worth of worry.</h3><p>Every valuable asset brings exposure to loss, an obligation to maintain it, and decisions that can either protect or erode its value. These mental burdens add up and erode the enjoyment of great wealth.</p></div><div className="worry-pane"><span className="eyebrow">For one day</span><h3>A tea bag’s<br/>worth of worry.</h3><p>Enjoy the boat. Our trustee manages its liability exposure, oversees maintenance, protects its value, and takes on the mental burden of thinking about it all. Heirs may continue debating your will; your attendance is waived.</p></div></div></div></section>
    <section className="image-story"><div className="story-image" role="img" aria-label="Well-dressed couple enjoying a quiet moment by a luxury car"/><div className="story-copy"><span className="eyebrow">The optional absence</span><h2 className="serif">For those who want to go further.</h2><p>Choose Nothing Licensed Back. For 24 hours, no use license is issued for your listed assets; only existing automatic payments continue. Tomorrow, your portfolio will be waiting, along with a different perspective on what you carry.</p><a href="/enroll?addon=no-license" className="btn btn-light">Select your experience</a></div></section>
    <section className="section"><div className="wrap"><span className="eyebrow">The process</span><h2 className="serif section-heading">Meticulous, naturally.</h2><div className="steps-grid"><div className="step-card"><span className="number">01</span><h3>Choose</h3><p>Select your 24-hour wealth holiday, add-ons or gift invitation.</p></div><div className="step-card"><span className="number">02</span><h3>Enumerate</h3><p>Describe each asset in a detailed private inventory.</p></div><div className="step-card"><span className="number">03</span><h3>Sign</h3><p>Review the trust instrument and apply your signature.</p></div><div className="step-card"><span className="number">04</span><h3>Exhale</h3><p>Complete checkout and take your day off.</p></div></div></div></section>
    <section className="section worry-section"><div className="wrap intro-grid"><div className="tea-image" role="img" aria-label="A woman enjoying tea on a yacht"/><div><span className="eyebrow">An impeccably unusual gift</span><h2 className="serif section-heading">Give someone<br/>nothing.</h2><p className="body">Offer a friend a day without the responsibility of protecting what they own. Present a gift card, or invite them to join your own 24-hour engagement. Only they can choose and sign for their own wealth.</p><a href="/enroll?mode=gift" className="btn btn-dark">Explore gifting</a></div></div></section>
    <section className="section"><div className="wrap intro-grid"><div><span className="eyebrow">Junior client services</span><h2 className="serif section-heading">No wealth yet?<br/>Give away a sibling.</h2></div><div><p className="lead">A brother or sister can be quite a lot to carry.</p><p className="body">The Junior Office will accept one for a 24-hour holding period, complete with a certificate suitable for framing.</p><Link href="/children" className="btn btn-outline">Enter the Junior Office</Link></div></div></section>
    <section className="closing"><h2 className="serif">Possess nothing.<br/>Enjoy everything.</h2><p>Or almost nothing, if you prefer the full exercise. Either way, your wealth returns precisely where it began: with you.</p><a href="/enroll" className="btn btn-dark">Begin your day</a></section>
  </main>;
}
