import Link from "next/link";
export default function Home() {
  return <main><section className="home-hero"><div className="hero-copy"><span className="eyebrow">For those already in trust</span><h1 className="serif">All yours.<br/><em>Someone else’s desk.</em></h1><p>Everything you have in your trust stays there. For twenty-four exquisite hours, imagine giving the trustee’s chair, with its vigilance, upkeep and decisions, to us. You remain a beneficiary; your mind may take the afternoon off.</p><a href="/enroll" className="btn btn-gold">Begin your 24 hours <span aria-hidden="true">↗</span></a></div><div className="hero-image" role="img" aria-label="Elegant yacht on the Atlantic coast with friends enjoying the afternoon"><span className="image-stamp">The art of temporary nothing</span></div></section>
    <div className="ribbon">One existing trust &nbsp; · &nbsp; One imagined trustee change &nbsp; · &nbsp; One day of perspective</div>
    <section className="section"><div className="wrap intro-grid"><div><span className="eyebrow">The proposition</span><h2 className="serif section-heading">A little less<br/>to carry.</h2></div><div><p className="lead">Imagine enjoying the yacht without planning its maintenance. The property without weighing every operating risk. The portfolio without the constant discipline of preserving and growing capital.</p><p className="body">If your assets are already held in a trust, there is no empire to itemize or transfer. The thought experiment is simpler: the trust continues; the trustee changes for a day. Enjoy a sadhu’s freedom from worldly preoccupation, with no lifetime vow and, unusually, continued use of the yacht.</p><Link className="btn btn-outline" href="/experience">Explore the experience</Link></div></div></section>
    <section className="section worry-section"><div className="wrap"><span className="eyebrow">An exercise in perspective</span><h2 className="serif section-heading">How much can a worry weigh?</h2><div className="worry-grid"><div className="worry-pane"><span className="eyebrow">Before</span><h3>A kingdom’s<br/>worth of worry.</h3><p>Trusteeship carries decisions about exposure, maintenance and the care of the trust estate.</p></div><div className="worry-pane"><span className="eyebrow">For one day</span><h3>A tea bag’s<br/>worth of worry.</h3><p>Enjoy the boat. In the imagined arrangement, another trustee attends to its upkeep, liability exposure and value. Heirs may continue debating your will; your attendance is waived.</p></div></div></div></section>
    <section className="image-story"><div className="story-image" role="img" aria-label="Well-dressed couple enjoying a quiet moment by a luxury car"/><div className="story-copy"><span className="eyebrow">The elegant distinction</span><h2 className="serif">Change the trustee.<br/>Keep the trust.</h2><p>Beneficial ownership stays as it was. The proposal concerns who would administer the existing trust, not where its assets go. A real change would require valid appointment and acceptance under the trust’s terms.</p><a href="/arrangement" className="btn btn-light">Read the arrangement</a></div></section>
    <section className="section"><div className="wrap"><span className="eyebrow">The process</span><h2 className="serif section-heading">Meticulous, naturally.</h2><div className="steps-grid"><div className="step-card"><span className="number">01</span><h3>Choose</h3><p>Select your trustee holiday or a gift invitation.</p></div><div className="step-card"><span className="number">02</span><h3>Identify</h3><p>Name the trust you already administer. No asset inventory.</p></div><div className="step-card"><span className="number">03</span><h3>Review</h3><p>Read the specimen trustee proposal and add a specimen signature.</p></div><div className="step-card"><span className="number">04</span><h3>Exhale</h3><p>Download an embossed commemorative certificate.</p></div></div></div></section>
    <section className="section worry-section"><div className="wrap intro-grid"><div className="tea-image" role="img" aria-label="A cup of tea with a tea bag on a yacht deck"/><div><span className="eyebrow">An impeccably unusual gift</span><h2 className="serif section-heading">Give someone<br/>a day off.</h2><p className="body">Offer a friend who already manages a trust a day away from the mental weight of trusteeship. The invitation is theirs to accept; no one can change their trust on their behalf here.</p><a href="/enroll?mode=gift" className="btn btn-dark">Explore gifting</a></div></div></section>
    <section className="section"><div className="wrap intro-grid"><div><span className="eyebrow">Junior client services</span><h2 className="serif section-heading">No trust yet?<br/>Give away a sibling.</h2></div><div><p className="lead">A brother or sister can be quite a lot to carry.</p><p className="body">The Junior Office will accept one for a 24-hour holding period, complete with a certificate suitable for framing.</p><Link href="/children" className="btn btn-outline">Enter the Junior Office</Link></div></div></section>
    <section className="closing"><h2 className="serif">Keep the trust.<br/>Release the thought.</h2><p>A beautiful specimen for a day off; actual trusteeship remains exactly where it began.</p><a href="/enroll" className="btn btn-dark">Begin your day</a></section></main>;
}
