"use client";

import { useEffect, useState } from "react";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import "../enroll/enroll.css";
import "./children.css";

export default function Children() {
  const [sibling, setSibling] = useState("brother");
  const [reason, setReason] = useState("Borrowing without asking");
  const [step, setStep] = useState(0);
  const [started, setStarted] = useState<Date | null>(null);
  useEffect(() => { window.scrollTo(0, 0); }, [step]);
  const confirm = () => { setStarted(new Date()); setStep(2); };
  return <main className="junior-page"><div className="junior-heading"><div className="wrap"><span className="eyebrow">The junior office of asset relief</span><h1 className="serif">No assets yet?<br/><em>No problem.</em></h1><p>Some fortunes are measured in siblings. For twenty-four hours, yours can be given away with all the ceremony it deserves.</p></div></div>
    <div className="wrap junior-layout"><div className="junior-panel">
      {step === 0 && <section><span className="eyebrow">01 / Identify the asset</span><h2 className="serif">Which sibling shall we take off your hands?</h2><RadioGroup value={sibling} onValueChange={setSibling} className="junior-options" aria-label="Choose sibling"><label className={"choice-card" + (sibling === "brother" ? " selected" : "")}><RadioGroupItem value="brother"/><span><strong className="serif">My brother</strong><small>Includes every annoying sound he makes.</small></span></label><label className={"choice-card" + (sibling === "sister" ? " selected" : "")}><RadioGroupItem value="sister"/><span><strong className="serif">My sister</strong><small>Includes strategic borrowing of my things.</small></span></label></RadioGroup><div className="field"><label>Primary reason for temporary disposal</label><Select value={reason} onValueChange={setReason}><SelectTrigger className="field-control"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Borrowing without asking">Borrowing without asking</SelectItem><SelectItem value="Eating the last cookie">Eating the last cookie</SelectItem><SelectItem value="Winning the remote control">Winning the remote control</SelectItem><SelectItem value="Being mysteriously favored">Being mysteriously favored</SelectItem><SelectItem value="General sibling behavior">General sibling behavior</SelectItem></SelectContent></Select></div><button className="btn btn-dark junior-action" onClick={() => setStep(1)}>Review the arrangement</button></section>}
      {step === 1 && <section><span className="eyebrow">02 / Junior private checkout</span><h2 className="serif">A very important transaction.</h2><div className="junior-deed"><div className="deed-top"><span className="brand-mark">G</span><span>JUNIOR DIVISION · 24-HOUR TERM</span></div><h3 className="serif">Certificate of Sibling Relinquishment</h3><p>For the next twenty-four hours, the Junior Office of Asset Relief shall hold one (1) {sibling}, surrendered for: <strong>{reason.toLowerCase()}</strong>.</p><p>The sibling will be returned at the end of the term, with no guarantee of improved manners.</p><div className="deed-rule"/><div className="summary-line"><span>Sibling handling</span><b>$0</b></div><div className="summary-line"><span>Paperwork</span><b>$0</b></div><div className="summary-total"><span>Amount due</span><b>$0</b></div></div><p className="junior-note">No names, email addresses or payment details are needed.</p><div className="panel-actions"><button className="btn btn-outline" onClick={() => setStep(0)}>Back</button><button className="btn btn-dark" onClick={confirm}>Give away my {sibling}</button></div></section>}
      {step === 2 && started && <section><span className="eyebrow">Junior transfer / complete</span><h2 className="serif">Your {sibling} has been given away.</h2><p className="junior-lead">Enjoy the quiet. We recommend using at least part of it before someone asks where the remote went.</p><div className="junior-certificate"><div className="gift-preview-top"><span className="brand-mark">G</span><span>JUNIOR DIVISION · REGISTERED</span></div><div className="serif junior-cert-title">One {sibling}.<br/>Twenty-four hours.<br/>Your peace.</div><div><span className="eyebrow">Reason on file</span><p>{reason}</p><span className="eyebrow">Scheduled return</span><p>{new Date(started.getTime() + 86400000).toLocaleString()}</p></div></div><div className="panel-actions"><button className="btn btn-outline" onClick={() => window.print()}>Print certificate</button><a href="/" className="btn btn-dark">Back to the estate</a></div></section>}
    </div><aside className="junior-aside"><span className="eyebrow">A modest holding</span><h2 className="serif">“Everything” is relative.</h2><p>Grown-ups list portfolios. Children have that one person who keeps touching their stuff.</p><div className="junior-aside-rule"/><span className="eyebrow">Standard term</span><strong>24 hours</strong><span className="eyebrow">Illustrative charge</span><strong>$0</strong></aside></div>
  </main>;
}
