"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Checkbox } from "@/components/ui/checkbox";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trustClauses } from "@/lib/trust-wording";
import { certificateSvg } from "@/lib/certificate-svg";
import "./enroll.css";

type Mode = "self" | "gift";
type Receipt = { number: string; started: Date };
const currency = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);

function Instrument({ trustName, currentTrustee, jurisdiction, signature, receipt }: { trustName: string; currentTrustee: string; jurisdiction: string; signature: string; receipt?: Receipt }) {
  return <div className="deed trust-instrument"><div className="deed-top"><span className="brand-mark">G</span><span>CLIENT SPECIMEN · NONBINDING</span></div><h3 className="serif">The Twenty-Four Hour<br/>Trustee Holiday</h3><p className="deed-sub">Proposed change of trustee · Existing trust{receipt && <> · {receipt.number}</>}</p><div className="deed-rule"/><p><b>Trust:</b> {trustName || "[Name of existing trust]"}</p><p><b>Current trustee:</b> {currentTrustee || "[Current trustee]"} · <b>Jurisdiction:</b> {jurisdiction || "[State]"}</p>{trustClauses().map((clause, index) => <p key={clause.title}><b>{index + 1}. {clause.title}.</b> {clause.text}</p>)}<div className="deed-rule"/><div className="instrument-signature"><span className="eyebrow">Participant signature preview</span><div className="signature-preview" aria-label="Signature preview">{signature || "Sign here"}</div><small>{receipt ? `Prepared ${receipt.started.toLocaleString()} · ${receipt.number}` : "Type your name below to preview it on this specimen."}</small></div></div>;
}

function Certificate({ mode, receipt, recipient, signature, billingName, giftNote, trustName }: { mode: Mode; receipt: Receipt; recipient: string; signature: string; billingName: string; giftNote: string; trustName: string }) {
  const gift = mode === "gift";
  return <div className="certificate embossed-certificate" aria-label="Commemorative certificate"><div className="certificate-inner"><div className="certificate-masthead"><span>GIVEAWAYMYWEALTH</span><span>PRIVATE CLIENT OFFICE · EST. FOR ONE DAY</span></div><div className="certificate-seal" aria-hidden="true"><span>G</span></div><p className="certificate-kicker">Certificate of {gift ? "an exceptional invitation" : "temporary relief"}</p><h3 className="serif certificate-title">{gift ? "The gift of a day off." : "A day without the weight of it all."}</h3><p className="certificate-presented">Presented with great ceremony to</p><p className="serif certificate-name">{gift ? recipient : signature}</p><div className="certificate-flourish" aria-hidden="true">✦</div><p className="certificate-description">{gift ? "An invitation for someone with an existing trust to imagine a 24-hour break from serving as trustee. They decide whether to participate." : <>For one day, the care of <b>{trustName}</b> is placed, in imagination, in other hands. Beneficial ownership stays where it is.</>}</p>{gift && giftNote && <p className="certificate-note">“{giftNote}”</p>}<div className="certificate-details"><div><small>{gift ? "Presented by" : "Prepared for"}</small><strong className="serif certificate-signature">{gift ? billingName : signature}</strong></div><div><small>Commemorative interval</small><strong>{receipt.started.toLocaleString()} – {new Date(receipt.started.getTime() + 86400000).toLocaleString()}</strong></div></div><div className="certificate-bottom"><span>NO. {receipt.number}</span><span>COMMEMORATIVE · NONBINDING · NO TRUSTEE APPOINTED</span></div></div></div>;
}

export default function Enroll() {
  const [step, setStep] = useState(0);
  const [mode, setMode] = useState<Mode>("self");
  const [companion, setCompanion] = useState(false);
  const [trustName, setTrustName] = useState("");
  const [currentTrustee, setCurrentTrustee] = useState("");
  const [jurisdiction, setJurisdiction] = useState("");
  const [allInTrust, setAllInTrust] = useState(false);
  const [signature, setSignature] = useState("");
  const [signAccepted, setSignAccepted] = useState(false);
  const [billingName, setBillingName] = useState("");
  const [billingEmail, setBillingEmail] = useState("");
  const [billingZip, setBillingZip] = useState("");
  const [recipient, setRecipient] = useState("");
  const [companionName, setCompanionName] = useState("");
  const [giftNote, setGiftNote] = useState("");
  const [payment, setPayment] = useState("card");
  const [checkoutAccepted, setCheckoutAccepted] = useState(false);
  const [error, setError] = useState("");
  const [receipt, setReceipt] = useState<Receipt | null>(null);
  const [copied, setCopied] = useState(false);
  useEffect(() => { const params = new URLSearchParams(window.location.search); if (params.get("mode") === "gift") setMode("gift"); if (params.get("addon") === "companion") setCompanion(true); }, []);
  useEffect(() => { window.scrollTo(0, 0); }, [step]);
  const total = 249 + (mode === "self" && companion ? 149 : 0);
  const flow = mode === "gift" ? [{ id: 0, name: "Selection" }, { id: 3, name: "Checkout" }] : [{ id: 0, name: "Selection" }, { id: 1, name: "Your trust" }, { id: 2, name: "Review" }, { id: 3, name: "Checkout" }];
  const currentIndex = flow.findIndex((item) => item.id === step);
  const download = receipt ? "data:image/svg+xml;charset=utf-8," + encodeURIComponent(certificateSvg({ mode, recipient, signature, billingName, giftNote, trustName, receipt })) : "";
  const next = (n: number) => { setError(""); setStep(n); };
  const trustNext = () => { if (!trustName.trim() || !currentTrustee.trim() || !jurisdiction.trim() || !allInTrust) { setError("Name your existing trust, its current trustee and jurisdiction, then confirm its scope."); return; } next(2); };
  const signNext = () => { if (!signature.trim() || !signAccepted) { setError("Type your name and acknowledge the specimen’s limits."); return; } setBillingName(signature.trim()); next(3); };
  const finish = () => { if (!billingName.trim() || !billingEmail.includes("@") || !/^\d{5}$/.test(billingZip)) { setError("Enter a name, email and five-digit ZIP code."); return; } if (mode === "gift" && !recipient.trim()) { setError("Enter a recipient name."); return; } if (companion && !companionName.trim()) { setError("Enter the companion’s name."); return; } if (!checkoutAccepted) { setError("Confirm the checkout terms."); return; } setReceipt({ number: "GMW-" + Math.random().toString(36).slice(2, 8).toUpperCase(), started: new Date() }); next(4); };
  const copyInvite = async () => { const name = mode === "gift" ? recipient : companionName; try { await navigator.clipboard.writeText(`A private invitation for ${name}: take an imaginary 24-hour break from serving as trustee of your existing trust at ${window.location.origin}/enroll. You decide whether to participate; this invitation changes no legal duties.`); setCopied(true); } catch { setCopied(false); } };
  return <main className="enroll-page"><div className="enroll-top"><div className="wrap"><span className="eyebrow">Private client services / enrollment</span><h1 className="serif">{step === 4 ? "Your day, beautifully unburdened." : "Give the trustee a day off."}</h1><p>Your assets are already in a trust. Identify the trust, review the proposed 24-hour change of trustee and receive a keepsake.</p></div></div><div className="wrap enroll-shell"><div className="enroll-main">
    {step !== 4 && <div className="progress-list" aria-label="Enrollment progress">{flow.map((item, index) => <div className={"progress-item" + (index === currentIndex ? " current" : "") + (index < currentIndex ? " done" : "")} key={item.id}><span>{String(index + 1).padStart(2, "0")}</span>{item.name}</div>)}</div>}
    {step === 0 && <section className="panel"><span className="eyebrow">01 / Select an experience</span><h2 className="serif panel-title">Who gets the day off?</h2><p className="panel-intro">For those already serving as trustee of their own trust. No inventory required.</p><RadioGroup value={mode} onValueChange={(v) => { setMode(v as Mode); if (v === "gift") setCompanion(false); }} className="mode-grid" aria-label="Experience recipient"><label className={"choice-card" + (mode === "self" ? " selected" : "")}><RadioGroupItem value="self"/><span><strong className="serif">For myself</strong><small>A 24-hour imagined change of trustee.</small></span></label><label className={"choice-card" + (mode === "gift" ? " selected" : "")}><RadioGroupItem value="gift"/><span><strong className="serif">As a gift</strong><small>An invitation for a trustee to take a day off.</small></span></label></RadioGroup><div className="selected-product"><div><span className="eyebrow">The signature experience</span><h3 className="serif">The Trustee Holiday</h3><p>The trust stays intact; the person at the desk changes in the story.</p></div><strong>$249</strong></div>{mode === "self" && <label className="addon-row"><Checkbox checked={companion} onCheckedChange={(v) => setCompanion(Boolean(v))}/><span><strong>The Companion Release</strong><small>Invite another trustee to consider their own trust separately.</small></span><b>+$149</b></label>}<div className="panel-actions"><button className="btn btn-dark" onClick={() => next(mode === "gift" ? 3 : 1)}>Continue</button></div></section>}
    {step === 1 && <section className="panel"><span className="eyebrow">02 / Existing trust</span><h2 className="serif panel-title">One trust. One day.</h2><p className="panel-intro">Enter only a general name and jurisdiction. Do not enter a trust document, account number, address or confidential information. These entries stay in this browser tab.</p><div className="field-grid"><div className="field full"><label htmlFor="trust-name">Name of existing trust *</label><Input id="trust-name" className="field-control" value={trustName} onChange={(e) => setTrustName(e.target.value)} placeholder="e.g. The Example Family Revocable Trust"/></div><div className="field"><label htmlFor="current-trustee">Current trustee *</label><Input id="current-trustee" className="field-control" value={currentTrustee} onChange={(e) => setCurrentTrustee(e.target.value)} placeholder="Your name"/></div><div className="field"><label htmlFor="jurisdiction">Governing state *</label><Input id="jurisdiction" className="field-control" value={jurisdiction} onChange={(e) => setJurisdiction(e.target.value)} placeholder="e.g. California"/></div></div><label className="confirm-row"><Checkbox checked={allInTrust} onCheckedChange={(v) => setAllInTrust(Boolean(v))}/><span>I am currently the trustee of an existing trust containing the assets I have in mind; I understand that property outside it is not covered by a trustee change.</span></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="panel-actions"><button className="btn btn-outline" onClick={() => next(0)}>Back</button><button className="btn btn-dark" onClick={trustNext}>Review specimen</button></div></section>}
    {step === 2 && <section className="panel"><span className="eyebrow">03 / Signing room</span><h2 className="serif panel-title">The fine print of freedom.</h2><p className="panel-intro">Review a proposed change of trustee for your existing trust. This preview has no legal effect.</p><Instrument trustName={trustName} currentTrustee={currentTrustee} jurisdiction={jurisdiction} signature={signature}/><div className="signature-area"><span className="eyebrow">Apply a specimen signature</span><div className="field"><label htmlFor="signature">Type your name</label><Input id="signature" className="field-control" value={signature} onChange={(e) => setSignature(e.target.value)} placeholder="Your name"/></div><label className="confirm-row"><Checkbox checked={signAccepted} onCheckedChange={(v) => setSignAccepted(Boolean(v))}/><span>I understand this is a nonbinding specimen: no trustee accepts office here, no duties or liabilities shift, and any real appointment requires a separate valid process.</span></label></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="panel-actions"><button className="btn btn-outline" onClick={() => next(1)}>Back to trust</button><button className="btn btn-dark" onClick={signNext}>Apply specimen signature</button></div></section>}
    {step === 3 && <section className="panel"><span className="eyebrow">{mode === "gift" ? "02" : "04"} / Checkout</span><h2 className="serif panel-title">The final formality.</h2><p className="panel-intro">No charge is processed and no details are sent from this browser tab.</p>{mode === "gift" && <div className="checkout-block"><h3 className="serif">Personalize the invitation</h3><div className="field-grid"><div className="field"><label htmlFor="recipient">Recipient name *</label><Input id="recipient" className="field-control" value={recipient} onChange={(e) => setRecipient(e.target.value)}/></div><div className="field full"><label htmlFor="gift-note">Note</label><Textarea id="gift-note" className="field-control" value={giftNote} onChange={(e) => setGiftNote(e.target.value)} rows={2}/></div></div></div>}{mode === "self" && companion && <div className="checkout-block"><h3 className="serif">Companion invitation</h3><div className="field"><label htmlFor="companion-name">Companion name *</label><Input id="companion-name" className="field-control" value={companionName} onChange={(e) => setCompanionName(e.target.value)}/></div></div>}<div className="checkout-block"><h3 className="serif">Contact & billing</h3><div className="field-grid"><div className="field"><label htmlFor="bill-name">Name *</label><Input id="bill-name" className="field-control" value={billingName} onChange={(e) => setBillingName(e.target.value)}/></div><div className="field"><label htmlFor="bill-email">Email *</label><Input id="bill-email" className="field-control" type="email" value={billingEmail} onChange={(e) => setBillingEmail(e.target.value)}/></div><div className="field"><label htmlFor="bill-zip">ZIP code *</label><Input id="bill-zip" className="field-control" inputMode="numeric" maxLength={5} value={billingZip} onChange={(e) => setBillingZip(e.target.value)}/></div></div><p className="input-note">Your entries remain here; no email is sent.</p></div><div className="checkout-block"><h3 className="serif">Payment preference</h3><RadioGroup value={payment} onValueChange={setPayment} aria-label="Payment preference"><label className="payment-option"><RadioGroupItem value="card"/><span><b>Reference card</b><small>•••• 4242 · no card details required</small></span></label><label className="payment-option"><RadioGroupItem value="invoice"/><span><b>Private client invoice</b><small>No invoice is issued</small></span></label></RadioGroup></div><label className="confirm-row"><Checkbox checked={checkoutAccepted} onCheckedChange={(v) => setCheckoutAccepted(Boolean(v))}/><span>I understand this checkout appoints no trustee, changes no trust terms or liabilities and takes no payment.</span></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="panel-actions"><button className="btn btn-outline" onClick={() => next(mode === "gift" ? 0 : 2)}>Back</button><button className="btn btn-dark" onClick={finish}>Complete checkout</button></div></section>}
    {step === 4 && receipt && <section className="panel confirmation"><span className="eyebrow">Client reference · {receipt.number}</span><h2 className="serif panel-title">{mode === "gift" ? "An extraordinary gift of nothing." : "For one day, somebody else’s desk."}</h2><p className="panel-intro">{mode === "gift" ? "Your invitation is ready. The recipient chooses whether to take part." : "Your commemorative 24-hour interval appears below. No trustee appointment occurred."}</p><Certificate mode={mode} receipt={receipt} recipient={recipient} signature={signature} billingName={billingName} giftNote={giftNote} trustName={trustName}/>{mode === "self" && <div className="completed-instrument"><h3 className="serif">Your specimen instrument</h3><p className="input-note">A nonbinding copy of the proposal you reviewed.</p><Instrument trustName={trustName} currentTrustee={currentTrustee} jurisdiction={jurisdiction} signature={signature} receipt={receipt}/></div>}{(mode === "gift" || companion) && <div className="invitation-actions"><p>Share a separate invitation; each person considers their own trust and signs only for themselves.</p><button className="btn btn-outline" onClick={copyInvite}>{copied ? "Invitation copied" : "Copy invitation text"}</button></div>}<div className="receipt-box"><div><span>Reference</span><b>{receipt.number}</b></div><div><span>Reference total</span><b>{currency(total)}</b></div><div><span>Amount charged</span><b>$0</b></div></div><p className="input-note">No legal appointment, purchase or asset transfer occurred. Your entries disappear when you leave or reload.</p><div className="panel-actions"><a className="btn btn-dark" href={download} download={"GiveAwayMyWealth-" + receipt.number + ".svg"}>Download certificate</a><button className="btn btn-outline" onClick={() => window.print()}>Print / save PDF</button><Link href="/" className="btn btn-outline">Return to the estate</Link></div></section>}
  </div><aside className="summary" aria-label="Order summary"><span className="eyebrow">Your selection</span><h2 className="serif">Twenty-four hours,<br/>beautifully arranged.</h2><div className="summary-line"><span>{mode === "gift" ? "Trustee Holiday gift" : "Trustee Holiday"}</span><b>$249</b></div>{mode === "self" && companion && <div className="summary-line"><span>Companion Release</span><b>$149</b></div>}<div className="summary-total"><span>Reference total</span><b>{currency(total)}</b></div><p>Reference prices. Actual amount charged: <strong>$0</strong>. This is a nonbinding experience.</p><Link href="/arrangement">Read the arrangement</Link></aside></div></main>;
}
