export default function Arrangement() {
  return <main><section className="arrangement-hero"><div className="wrap narrow"><span className="eyebrow">The arrangement, explained</span><h1 className="serif section-heading">The trust stays.<br/>The trustee takes a day off.</h1><p className="large-copy">For people whose assets are already in a trust and who currently serve as its trustee.</p></div></section><section className="section"><div className="wrap clauses">
    <div className="clause"><span>01 / THE EXISTING TRUST</span><div><h2 className="serif">No new inventory.</h2><p>Identify the trust you already administer. Its assets and beneficiaries are not moved into a new trust. An asset outside the existing trust would not be covered by changing its trustee.</p></div></div>
    <div className="clause"><span>02 / THE PROPOSED CHANGE</span><div><h2 className="serif">A different name at the desk.</h2><p>The experience imagines GiveAwayMyWealth serving as trustee for 24 hours, then your return to the office. A real appointment would depend on the trust document, trustee eligibility, a valid appointment and acceptance, and any required notice or account updates.</p></div></div>
    <div className="clause"><span>03 / OWNERSHIP</span><div><h2 className="serif">The beneficial interests stay put.</h2><p>A trustee change alone does not give the trustee beneficial ownership. California generally excludes substitution of a trustee from property-tax reassessment when beneficial interests do not change. Other consequences depend on the trust and the facts.</p></div></div>
    <div className="clause"><span>04 / THE 24 HOURS</span><div><h2 className="serif">Care has a job description.</h2><p>An actual trustee has duties to administer the trust; a former trustee is not automatically released from previous acts or personal obligations. Returning to office after a day also needs a valid succession process. Time on a certificate does not do that work.</p></div></div>
    <div className="clause"><span>05 / THE KEEPSAKE</span><div><h2 className="serif">Beautiful paper, modest power.</h2><p>Our browser-only specimen, checkout and certificate appoint no trustee and transfer no duties, access or liability. The gift invites another person to imagine the same holiday for their own trust.</p><p><a href="https://www.boe.ca.gov/proptaxes/faqs/changeinownership.htm">California Board of Equalization: change in ownership</a> · <a href="https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?article=3.&chapter=1.&division=9.&lawCode=PROB&part=3.&title=">California Probate Code: trustee succession</a></p></div></div>
  </div></section><section className="closing"><h2 className="serif">Ready to put the office down?</h2><p>The trust can stay exactly where it is.</p><a href="/enroll" className="btn btn-dark">Begin your day</a></section></main>;
}
